### ISSUE TITLE
Unable to compile in Ubuntu 14.04?

### ISSUE THREAD

**Issue by bihonglu** [zakki/Ray#5]
I was trying to compile the RN 3.9 in Ubuntu linux 14.04 but failed.   What did I do wrong here? 
Any help would be greatly appreciated. 

Here is detailed information: 
Hardware:  dual core Indel box, Ubuntu 14.04 64 bits.   1 GPU with GTX 1050
CUDA/torch/cntk  all dependency were compiled and installed with no errors. 

g++  version 4.8 

In the compilation of RN 3.9 source code after make, below are the errors: 
------skipped---------------
g++ -O3 -Wall -std=c++11 -g -c src/Point.cpp -o src/Point.o
g++ -O3 -Wall -std=c++11 -g -c src/Rating.cpp -o src/Rating.o
src/Rating.cpp: In function \u2018int RatingMove(game_info_t*, int, std::mt19937_64*, LGR&)\u2019:
src/Rating.cpp:290:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (((*mt)() % 100) < tgr1_rate && game->moves > 0) {
                           ^
src/Rating.cpp:291:14: error: \u2018atomic_int64_t\u2019 in namespace \u2018std\u2019 does not name a type
       static std::atomic_int64_t lgr_total;
              ^
src/Rating.cpp:292:14: error: \u2018atomic_int64_t\u2019 in namespace \u2018std\u2019 does not name a type
       static std::atomic_int64_t lgr_hit;
              ^
src/Rating.cpp:293:30: error: \u2018lgr_total\u2019 was not declared in this scope
       std::atomic_fetch_add(&lgr_total, 1);
                              ^
src/Rating.cpp:298:25: error: \u2018lgr_hit\u2019 was not declared in this scope
  std::atomic_fetch_add(&lgr_hit, 1);
                         ^
src/Rating.cpp:304:30: error: \u2018lgr_hit\u2019 was not declared in this scope
  cerr << "TGR1 " << (100.0 * lgr_hit / lgr_total) << "%" << std::endl;
                              ^
src/Rating.cpp:307:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (((*mt)() % 100) < lgrf1_rate && game->moves > 0) {
                           ^
src/Rating.cpp:308:14: error: \u2018atomic_int64_t\u2019 in namespace \u2018std\u2019 does not name a type
       static std::atomic_int64_t lgr_total;
              ^
src/Rating.cpp:309:14: error: \u2018atomic_int64_t\u2019 in namespace \u2018std\u2019 does not name a type
       static std::atomic_int64_t lgr_hit;
              ^
src/Rating.cpp:310:30: error: \u2018lgr_total\u2019 was not declared in this scope
       std::atomic_fetch_add(&lgr_total, 1);
                              ^
src/Rating.cpp:314:25: error: \u2018lgr_hit\u2019 was not declared in this scope
  std::atomic_fetch_add(&lgr_hit, 1);
                         ^
src/Rating.cpp:320:31: error: \u2018lgr_hit\u2019 was not declared in this scope
  cerr << "LGRF1 " << (100.0 * lgr_hit / lgr_total) << "%" << std::endl;
                               ^
src/Rating.cpp:325:14: error: \u2018atomic_int64_t\u2019 in namespace \u2018std\u2019 does not name a type
       static std::atomic_int64_t lgr_total;
              ^
src/Rating.cpp:326:14: error: \u2018atomic_int64_t\u2019 in namespace \u2018std\u2019 does not name a type
       static std::atomic_int64_t lgr_hit;
              ^
src/Rating.cpp:327:30: error: \u2018lgr_total\u2019 was not declared in this scope
       std::atomic_fetch_add(&lgr_total, 1);
                              ^
src/Rating.cpp:332:25: error: \u2018lgr_hit\u2019 was not declared in this scope
  std::atomic_fetch_add(&lgr_hit, 1);
                         ^
src/Rating.cpp:339:29: error: \u2018lgr_hit\u2019 was not declared in this scope
  cerr << "LGRF2 " << (100 * lgr_hit / lgr_total) << "%" << std::endl;
                             ^
make: *** [src/Rating.o] Error 1

**Comment by zakki** [comment]
`std::atomic_int64_t` seems to be nonstandard yet.
https://gcc.gnu.org/ml/libstdc++/2016-07/txtDBj7B13FET.txt

Does `typedef` solve error?
```
typedef atomic<int64_t>		atomic_int64_t;
```

**Comment by bihonglu** [comment]
Thanks for responding to my question.  Nope, the typedef did not work.  I placed typedef below the std definition as below:
using namespace std;
typedef atomic<int64_t>		atomic_int64_t;

Recompile with same error

**Comment by zakki** [comment]
Perphaps I need to replace `static std::atomic_int64_t ...`  with  `static atomic_int64_t ...`.

**Comment by bihonglu** [comment]
in Rating.cpp,  just replaced static std::atomic_int64_t ... with static atomic_int64_t, recompile, 
got a different sets of errors as below: 


g++ -O3 -Wall -std=c++11 -g -c src/Point.cpp -o src/Point.o
g++ -O3 -Wall -std=c++11 -g -c src/Rating.cpp -o src/Rating.o
src/Rating.cpp: In function \u2018int RatingMove(game_info_t*, int, std::mt19937_64*, LGR&)\u2019:
src/Rating.cpp:292:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (((*mt)() % 100) < tgr1_rate && game->moves > 0) {
                           ^
src/Rating.cpp:295:42: error: no matching function for call to \u2018atomic_fetch_add(atomic_int64_t*, int)\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:295:42: note: candidates are:
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1024:5: note: template<class _ITp> _ITp std::atomic_fetch_add(std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(__atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1024:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:295:42: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1029:5: note: template<class _ITp> _ITp std::atomic_fetch_add(volatile std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(volatile __atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1029:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:295:42: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1088:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(volatile std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(volatile atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1088:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:295:42: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:295:42: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018volatile std::atomic<_Tp*>\u2019
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1093:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1093:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:295:42: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:295:42: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018std::atomic<_Tp*>\u2019
src/Rating.cpp:300:35: error: no matching function for call to \u2018atomic_fetch_add(atomic_int64_t*, int)\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:300:35: note: candidates are:
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1024:5: note: template<class _ITp> _ITp std::atomic_fetch_add(std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(__atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1024:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:300:35: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1029:5: note: template<class _ITp> _ITp std::atomic_fetch_add(volatile std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(volatile __atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1029:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:300:35: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1088:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(volatile std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(volatile atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1088:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:300:35: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:300:35: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018volatile std::atomic<_Tp*>\u2019
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1093:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1093:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:300:35: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:300:35: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018std::atomic<_Tp*>\u2019
src/Rating.cpp:309:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (((*mt)() % 100) < lgrf1_rate && game->moves > 0) {
                           ^
src/Rating.cpp:312:42: error: no matching function for call to \u2018atomic_fetch_add(atomic_int64_t*, int)\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:312:42: note: candidates are:
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1024:5: note: template<class _ITp> _ITp std::atomic_fetch_add(std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(__atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1024:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:312:42: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1029:5: note: template<class _ITp> _ITp std::atomic_fetch_add(volatile std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(volatile __atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1029:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:312:42: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1088:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(volatile std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(volatile atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1088:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:312:42: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:312:42: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018volatile std::atomic<_Tp*>\u2019
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1093:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1093:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:312:42: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:312:42: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018std::atomic<_Tp*>\u2019
src/Rating.cpp:316:35: error: no matching function for call to \u2018atomic_fetch_add(atomic_int64_t*, int)\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:316:35: note: candidates are:
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1024:5: note: template<class _ITp> _ITp std::atomic_fetch_add(std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(__atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1024:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:316:35: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1029:5: note: template<class _ITp> _ITp std::atomic_fetch_add(volatile std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(volatile __atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1029:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:316:35: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1088:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(volatile std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(volatile atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1088:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:316:35: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:316:35: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018volatile std::atomic<_Tp*>\u2019
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1093:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1093:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:316:35: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:316:35: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018std::atomic<_Tp*>\u2019
src/Rating.cpp:329:42: error: no matching function for call to \u2018atomic_fetch_add(atomic_int64_t*, int)\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:329:42: note: candidates are:
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1024:5: note: template<class _ITp> _ITp std::atomic_fetch_add(std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(__atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1024:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:329:42: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1029:5: note: template<class _ITp> _ITp std::atomic_fetch_add(volatile std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(volatile __atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1029:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:329:42: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1088:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(volatile std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(volatile atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1088:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:329:42: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:329:42: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018volatile std::atomic<_Tp*>\u2019
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1093:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1093:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:329:42: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
       std::atomic_fetch_add(&lgr_total, 1);
                                          ^
src/Rating.cpp:329:42: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018std::atomic<_Tp*>\u2019
src/Rating.cpp:334:35: error: no matching function for call to \u2018atomic_fetch_add(atomic_int64_t*, int)\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:334:35: note: candidates are:
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1024:5: note: template<class _ITp> _ITp std::atomic_fetch_add(std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(__atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1024:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:334:35: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1029:5: note: template<class _ITp> _ITp std::atomic_fetch_add(volatile std::__atomic_base<_ITp>*, _ITp)
     atomic_fetch_add(volatile __atomic_base<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.8/atomic:1029:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:334:35: note:   deduced conflicting types for parameter \u2018_ITp\u2019 (\u2018long int\u2019 and \u2018int\u2019)
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1088:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(volatile std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(volatile atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1088:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:334:35: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:334:35: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018volatile std::atomic<_Tp*>\u2019
In file included from src/UctSearch.h:4:0,
                 from src/Message.h:6,
                 from src/Rating.cpp:13:
/usr/include/c++/4.8/atomic:1093:5: note: template<class _ITp> _ITp* std::atomic_fetch_add(std::atomic<_Tp*>*, std::ptrdiff_t)
     atomic_fetch_add(atomic<_ITp*>* __a, ptrdiff_t __d) noexcept
     ^
/usr/include/c++/4.8/atomic:1093:5: note:   template argument deduction/substitution failed:
src/Rating.cpp:334:35: note:   mismatched types \u2018_Tp*\u2019 and \u2018long int\u2019
  std::atomic_fetch_add(&lgr_hit, 1);
                                   ^
src/Rating.cpp:334:35: note:   \u2018atomic_int64_t {aka std::atomic<long int>}\u2019 is not derived from \u2018std::atomic<_Tp*>\u2019
make: *** [src/Rating.o] Error 1

**Comment by zakki** [comment]
Does `x.fetch_add(1)` work?
http://stackoverflow.com/questions/25332245/stdatomicint-difference-between-x-fetch-add1-and-x

Also removing those atomic_int64_t related code would work, because those variables are used to print debug messages.

**Comment by bihonglu** [comment]
replaced       std::atomic_fetch_add(&lgr_total, 1);
	std::atomic_fetch_add(&lgr_hit, 1);
with       lgr_total.fetch_add(1);
	lgr_hit.fetch_add(1);
It passed Rating.cpp.  New error popped up: 
g++ -O3 -Wall -std=c++11 -g -c src/Simulation.cpp -o src/Simulation.o
g++ -O3 -Wall -std=c++11 -g -c src/UctRating.cpp -o src/UctRating.o
src/UctRating.cpp:82:15: warning: \u2018criticality_init\u2019 defined but not used [-Wunused-variable]
 static double criticality_init = CRITICALITY_INIT;
               ^
g++ -O3 -Wall -std=c++11 -g -c src/UctSearch.cpp -o src/UctSearch.o
src/UctSearch.cpp:39:18: fatal error: Eval.h: No such file or directory
 #include "Eval.h"
                  ^
compilation terminated.
make: *** [src/UctSearch.o] Error 1

It appears that the file Eval.h  is missing in the source.

**Comment by zakki** [comment]
Thanks.

`Eval.h` comes from CNTK.
Maybe Makefile needs something like `CFLAGS = ${OPTIMIZE} ${WARNING} ${CPP11} ${DEBUG} -I/foo/bar/cntk/include`.

**Comment by bihonglu** [comment]
Modified the Makefile, got error  as below: 
src/UctRating.cpp:82:15: warning: \u2018criticality_init\u2019 defined but not used [-Wunused-variable]
 static double criticality_init = CRITICALITY_INIT;
               ^
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -c src/UctSearch.cpp -o src/UctSearch.o
src/UctSearch.cpp: In function \u2018void UctSearchStat(game_info_t*, int, int)\u2019:
src/UctSearch.cpp:713:10: warning: variable \u2018pass_wp\u2019 set but not used [-Wunused-but-set-variable]
   double pass_wp;
          ^
src/UctSearch.cpp:714:10: warning: variable \u2018best_wp\u2019 set but not used [-Wunused-but-set-variable]
   double best_wp;
          ^
src/UctSearch.cpp:716:7: warning: variable \u2018pre_simulated\u2019 set but not used [-Wunused-but-set-variable]
   int pre_simulated;
       ^
src/UctSearch.cpp: In function \u2018int SelectMaxUcbChild(const game_info_t*, int, int)\u2019:
src/UctSearch.cpp:1595:6: warning: unused variable \u2018pos\u2019 [-Wunused-variable]
  int pos = uct_child[i].pos;
      ^
src/UctSearch.cpp: In function \u2018void EvalPolicy(const std::vector<std::shared_ptr<policy_eval_req> >&, std::vector<float>&)\u2019:
src/UctSearch.cpp:2177:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int j = 0; j < requests.size(); j++) {
                                     ^
src/UctSearch.cpp: In function \u2018void EvalValue(const std::vector<std::shared_ptr<value_eval_req> >&, std::vector<float>&)\u2019:
src/UctSearch.cpp:2272:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int j = 0; j < requests.size(); j++) {
                                     ^
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -c src/Utility.cpp -o src/Utility.o
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -c src/ZobristHash.cpp -o src/ZobristHash.o
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -o ray src/Command.o src/DynamicKomi.o src/GoBoard.o src/Gtp.o src/Ladder.o src/Message.o src/Nakade.o src/Pattern.o src/PatternHash.o src/Point.o src/Rating.o src/RayMain.o src/Semeai.o src/Simulation.o src/UctRating.o src/UctSearch.o src/Utility.o src/ZobristHash.o -lm -pthread 
src/UctSearch.o: In function `ReadWeights()':
/home/honglu/src/Ray-rn-3.9/src/UctSearch.cpp:2133: undefined reference to `GetEvalF'
collect2: error: ld returned 1 exit status
make: *** [ray] Error 1

**Comment by zakki** [comment]
It seems that `libeval` and other libraries have to be linked. https://github.com/Microsoft/CNTK/blob/master/Makefile#L546
`LIBS = -lm -pthread -leval ...`

**Comment by bihonglu** [comment]
Still got error as below: 
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -c src/ZobristHash.cpp -o src/ZobristHash.o
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -o ray src/Command.o src/DynamicKomi.o src/GoBoard.o src/Gtp.o src/Ladder.o src/Message.o src/Nakade.o src/Pattern.o src/PatternHash.o src/Point.o src/Rating.o src/RayMain.o src/Semeai.o src/Simulation.o src/UctRating.o src/UctSearch.o src/Utility.o src/ZobristHash.o -lm -pthread -leval 
/usr/bin/ld: cannot find -leval
collect2: error: ld returned 1 exit status
make: *** [ray] Error 1

The  LD path looks good: 
 :~$ echo $LD_LIBRARY_PATH
/home/honglu/cntk/cntk/lib:/home/honglu/cntk/cntk/dependencies/lib:/home/honglu/openmpi/lib:/home/honglu/torch/install/lib:/usr/local/cuda-8.0/lib64:
libeval.so  file is there below /home/honglu/cntk/cntk/lib. 
I even put the lib path under ldconfig  files to make them available.  Still the compiling does not work.

**Comment by bihonglu** [comment]
Tried -static-libstdc++ -static-libgcc  ,  same error as below:
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -c src/ZobristHash.cpp -o src/ZobristHash.o
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -o ray src/Command.o src/DynamicKomi.o src/GoBoard.o src/Gtp.o src/Ladder.o src/Message.o src/Nakade.o src/Pattern.o src/PatternHash.o src/Point.o src/Rating.o src/RayMain.o src/Semeai.o src/Simulation.o src/UctRating.o src/UctSearch.o src/Utility.o src/ZobristHash.o -static-libstdc++ -static-libgcc
src/UctSearch.o: In function `ReadWeights()':
/home/honglu/src/Ray-rn-3.9/src/UctSearch.cpp:2133: undefined reference to `GetEvalF'
collect2: error: ld returned 1 exit status
make: *** [ray] Error 1

**Comment by zakki** [comment]
I think LD_LIBRARY_PATH isn't used compile time but runtime. What happen with `-L/home/honglu/cntk/cntk/lib` ?

**Comment by bihonglu** [comment]
Still does not work.  I added 2 more lib folders, still same error:
g++ -O3 -Wall -std=c++11 -g -I/home/honglu/cntk/Include -o ray src/Command.o src/DynamicKomi.o src/GoBoard.o src/Gtp.o src/Ladder.o src/Message.o src/Nakade.o src/Pattern.o src/PatternHash.o src/Point.o src/Rating.o src/RayMain.o src/Semeai.o src/Simulation.o src/UctRating.o src/UctSearch.o src/Utility.o src/ZobristHash.o -lm -pthread -L/home/honglu/cntk/cntk/lib -L/home/honglu/cntk/cntk/dependencies/lib -L/home/honglu/openmpi/lib
src/UctSearch.o: In function `ReadWeights()':
/home/honglu/src/Ray-rn-3.9/src/UctSearch.cpp:2133: undefined reference to `GetEvalF'
collect2: error: ld returned 1 exit status
make: *** [ray] Error 1

**Comment by zakki** [comment]
Perhaps both `-L<dir> -leval` are needed.

**Comment by bihonglu** [comment]
Hi Kensuke, 
Fantastic!  I got ray compiled successfully.  I will test it out and potentially put it online at DGS soon. 
Anyway,  many thanks to you for making this wonderful go AI open source and available for go communities world wide. 

Hong

**Comment by zakki** [comment]
😄

**Comment by bihonglu** [comment]
Just let you know that  I put  RN3.9 at DGS with 5 Dan initial assessment by myself: 
http://www.dragongoserver.net/userinfo.php?uid=97868

**Comment by zakki** [comment]
Thanks.
Current rn has some obvious week points at seki, nakade fighting and ladder.
I'm interested in what level critical those are when playing with strong human player.

**Comment by zakki** [comment]
Fixed some problems. It seems OK in Ubuntu 14.04 Deep Learning AMI Ubuntu Version.

**Comment by emdio** [comment]
I know this issue is closed, but I don't find a way to contact bihonglu; I'd just like to ask him the Makefile or the complete compile command with which he got to compile RayOn.
